### ISSUE TITLE
Installation of themes does not work. Modules ask for theme.

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-EasyInstall#1]
Hi,

I have an error ("There was an error on the form. Please try again.") when I select only a module or a theme. 

If I select both a theme and a module, the module is installed but not the theme.

So I can't install theme and I can only install module by selecting a theme which will not be installed.

Another unrelated question: do this plugin support upgrade of a module?

**Comment by Daniel-KM** [comment]
Hi,

Thanks for your report. This is fixed.

This is an idea added to my todo list, but Omeka S is still in a beta phase, so it's a bit soon to upgrade modules... 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
