### ISSUE TITLE
Cannot install from Omeka.org

### ISSUE THREAD

**Issue by brimwats1** [Daniel-KM/Omeka-S-module-EasyInstall#3]
Tried to install new CSVImport, Mapping, ValueSuggest, Zotero and Hide modules from Omeka.org today, but it just loads, refreshes and doesn't install. 

Modules Web still works but those ones are outdated.

**Comment by Daniel-KM** [comment]
The module is not yet updated for last version of the omeka site data.

**Comment by brimwats1** [comment]
Thanks Daniel. I realized this and forgot to close.

**Comment by Daniel-KM** [comment]
This is fixed and updated for Omeka 2.

**Comment by brimwats1** [comment]
Thanks for the update!!


BRIAN M. WATSON
they/them
twitter<https://twitter.com/HoP_Twte>  -  email<mailto:bmwatson1989@gmail.com>  -  website<https://brimwats.com/>
Archivist-Historian: APA Division 44 CNM<https://www.div44cnm.org/>
Graduate Archivist: Kinsey Institute Library<https://kinseyinstitute.org/collections/index.php>


________________________________
