### ISSUE TITLE
Error: the module is in the database, but not in the file system

### ISSUE THREAD

**Issue by jgomcat** [Daniel-KM/Omeka-S-module-EasyInstall#7]
Hello Dani,

I have recently updated Omeka to 3.1.1 version. The problem is that in all modules say 'Error: the module is in the database, but not in the file system'. 

![Error_Omeka](https://user-images.githubusercontent.com/97663934/152992809-021e01ce-7509-4f82-9f3a-7d2e780b2671.jpg)

How can I solve this?

Thanks.

**Comment by Daniel-KM** [comment]
You can rename the folders of the module, removing begin of the name: the name should be "AdvancedSearchPlus" instead of "Omeka-S-module-AdvancedSearchPlus".

**Comment by Daniel-KM** [comment]
And AdvancedSearchPlus has been replaced by AdvancedSearch.
